---
# tasks file for inverso.confluence-docker

- name: check required variables
  assert:
    that:
      - confluence_data_dir                 | mandatory
      - confluence_version                  | mandatory
      - confluence_jvm_min_mem              | mandatory
      - confluence_jvm_max_mem              | mandatory
      - confluence_support_recommended_args | mandatory
      - confluence_servername               | mandatory
      - confluence_service_enabled          in ['yes','no']
  tags: ['varcheck']

- name: ensure docker is present
  package:
    name: docker
    state: present

- name: ensure docker is started and enabled
  systemd:
    name: docker
    enabled: '{{ confluence_service_enabled }}'
    state: started

- name: create confluence data dir on docker host
  file:
    path: '{{ confluence_data_dir }}'
    state: directory

- name: ensure system cacerts file is also present for confluence
  copy:
    src: '/etc/pki/java/cacerts'
    dest: '{{ confluence_data_dir }}/'
    remote_src: yes

# FIXME: try to limit exposed ports to 127.0.0.1 only
- name: create confluence container
  docker_container:
    name: 'confluence'
    hostname: 'confluence'
    image: "{{ confluence_image_registry }}{{ confluence_image_registry | ternary('/','') }}{{ confluence_image_name }}:{{ confluence_version }}"
    state: "{{ (confluence_service_enabled == 'yes') | ternary('started','stopped') }}"
    restart_policy: unless-stopped
    cacert_path: '/etc/pki/tls/certs/ca-bundle.crt'
    network_mode: host
    volumes:
      - '{{ confluence_data_dir }}:/var/atlassian/application-data/confluence'
    env:
      LANG: 'de_DE.utf8'
      JVM_MINIMUM_MEMORY: '{{ confluence_jvm_min_mem }}'
      JVM_MAXIMUM_MEMORY: '{{ confluence_jvm_max_mem }}'
      JVM_SUPPORT_RECOMMENDED_ARGS: '{{ confluence_support_recommended_args }}'
      ATL_PROXY_NAME: '{{ confluence_revproxy_name }}'
      ATL_PROXY_PORT: '{{ confluence_revproxy_port }}'
      ATL_TOMCAT_SCHEME: '{{ confluence_revproxy_scheme }}'
      ATL_TOMCAT_SECURE: '{{ confluence_revproxy_secure }}'
      ATL_TOMCAT_CONTEXTPATH: '{{ confluence_webappcontextpath }}'
